### ISSUE TITLE
maybe you should have a look at

### ISSUE THREAD

**Issue by l3pp4rd** [sittercity/gocumber#20]
https://github.com/DATA-DOG/godog

**Comment by ppeble** [comment]
Yep! We heard about this at the same time as we heard about gucumber. Neither were around last fall when we started on this and to be honest up until now it was serving our purposes internally, even with the missing runner.

Yesterday at the Gophercon hackday we actually made a few tests both with godog and gucumber, ripping out gocumber and using the other ones instead. Hopefully this week we'll have some feedback and we can consolidate. We have a few use cases that we would like to see but it makes a lot more sense to integrate those use cases with one or both of your tools instead of trying to catch up.

Thanks for the note! Expect some issues/PRs in the near future. :smile:
